### ISSUE TITLE
Allow other database types

### ISSUE THREAD

**Issue by michaelmior** [schn4ck/schnack#52]
While I agree SQLite is suitable in terms of scalability for most blogs for a long time, it complicates deployment on many platforms (e.g. Heroku). Would you be open to accepting a PR to support some kind of abstraction layer which would still allow SQLite, but also other DBs?

**Comment by g-div** [comment]
We can talk about that, but the simplest solution to me seems to be to deploy schnack somewhere else! 
Such a small project isn't really though to be used with an huge and complex DBMS, I think.

I've worked with a lot of ORM/ODMs with multiple adapters in the past and while I really like the concept, I was also really discouraged by their real implementation. In real life I was often struggling with issues related to the library I've chose, instead of concentrate myself on the real data-flow.

IMHO this is not worth for schnack, which should remain small and concise, exploiting all features offered by a SQLite (we already use some) instead of adding a new larger set of unused features.

Which *abstraction layer* would you propose ? For which database ?

**Comment by michaelmior** [comment]
I'll admit that the main reason I want this is specifically for Heroku and specifically because they have a free tier that would be sufficient for my needs. As for which abstraction layer, [Sequelize](https://github.com/sequelize/sequelize) seems to be the most popular. [Knex](https://github.com/tgriesser/knex) also seems like a reasonable option.

**Comment by gka** [comment]
@michaelmior  on Heroku, can't you just store the SQlite db in `/tmp` and somehow sync this file with S3 to keep it permanently?

**Comment by michaelmior** [comment]
@gka You can store the file there, but you would have to back up every time you write. Heroku instances could shut down at any time and there's no way to ensure things are backed up.

**Comment by g-div** [comment]
I'm not sure that SQLite is the only problem we will encounter adapting schnack to run on Heroku. Heroku's dynos are thought to be stateless processes, also because of the ephemeral nature of the filesystem, and we are also using in-memory storage solutions. We did that having in mind that schnack isn't intended to scale past a single process, so an in-memory solution would have been fine.

I'm increasingly thinking that schnack and heroku aren't done to work togheter...

**Comment by michaelmior** [comment]
Fair enough. Sounds like schnack isn't what I'm looking for. Thanks!
